### ISSUE TITLE
"Support us with your donation" URL in footer is broken

### ISSUE THREAD

**Issue by willyogo** [Giveth/giveth-next#291]
Currently the "Support us with your donation" text link in the footer routes to https://giveth.io/donate/giveth which returns 'Not Found'

It should route to https://giveth.io/donate/the-giveth-community-of-makers

AC:
1. When a user clicks 'Support us with your donation' they see the Giveth donation page

**Comment by willyogo** [comment]
> @willyogo would u pls trasfer this to giveth-next? I dint have access to this board. Thanks

yes ty @MoeNick ! transferring now

**Comment by RamRamez** [comment]
Done in PR #315

**Comment by willyogo** [comment]
Thanks for fixing @RamRamez! Has this been deployed yet? I'm still seeing this issue on https://giveth.io as of Oct 31

**Comment by MoeNick** [comment]
@willyogo I think its fixed in uat, we soon may have a release on Production .

**Comment by willyogo** [comment]
awesome thanks @MoeNick! 💜

**Comment by DonnaOftadeh** [comment]
@RamRamez @MoeNick I tested it on next and it is still not working:
![image](https://user-images.githubusercontent.com/53400757/144045988-eb7b4877-9997-43a8-a471-48513f562331.png)

**Comment by divine-comedian** [comment]
testing on `next.giveth.io` and `giveth.io` 

I can see that on staging this link goes to - https://next.giveth.io/donate/giveth-2021:-retreat-to-the-future

and on production - https://giveth.io/donate/the-giveth-community-of-makers

no more 404 errors! looks to be resolved.
